import type { GameData } from "@/game/types";

/** 仅用于开发页面预览的固定演示数据。 */
export const fakeGameData: GameData = {
  gold: 12800,
  actors: [
    {
      id: 1,
      name: "艾莉亚",
      classId: 1,
      level: 12,
      exp: 1840,
      mhp: 620,
      mmp: 180,
      tp: 30,
      atk: 78,
      def: 64,
      mat: 52,
      mdf: 48,
      agi: 70,
      luk: 35,
      inTeam: true,
    },
    {
      id: 2,
      name: "诺亚",
      classId: 2,
      level: 10,
      exp: 1320,
      mhp: 420,
      mmp: 360,
      tp: 18,
      atk: 42,
      def: 38,
      mat: 92,
      mdf: 76,
      agi: 55,
      luk: 41,
      inTeam: true,
    },
    {
      id: 3,
      name: "米娅",
      classId: 3,
      level: 8,
      exp: 760,
      mhp: 510,
      mmp: 120,
      tp: 45,
      atk: 66,
      def: 45,
      mat: 35,
      mdf: 40,
      agi: 96,
      luk: 68,
      inTeam: false,
    },
  ],
  armors: [
    { id: 1, name: "旅行者外套", playerHasCount: 1 },
    { id: 2, name: "银制胸甲", playerHasCount: 0 },
    { id: 3, name: "贤者长袍", playerHasCount: 1 },
  ],
  items: [
    { id: 1, name: "回复药", playerHasCount: 8 },
    { id: 2, name: "魔力药", playerHasCount: 3 },
    { id: 3, name: "解毒草", playerHasCount: 5 },
    { id: 4, name: "古老钥匙", playerHasCount: 1 },
  ],
  weapons: [
    { id: 1, name: "铁剑", playerHasCount: 1 },
    { id: 2, name: "月桂法杖", playerHasCount: 1 },
    { id: 3, name: "猎人短弓", playerHasCount: 0 },
  ],
  isEncounterEnabled: true,
  isFormationEnabled: true,
  variables: [
    { id: 1, variablesKey: "主线进度", variablesValue: 4 },
    { id: 2, variablesKey: "好感度", variablesValue: 25 },
    { id: 3, variablesKey: "当前地区", variablesValue: "风之谷" },
  ],
  switches: [
    { id: 1, switchesKey: "序章完成", switchesValue: true },
    { id: 2, switchesKey: "隐藏商店开放", switchesValue: false },
    { id: 3, switchesKey: "夜间模式", switchesValue: false },
  ],
  classes: [
    { id: 1, name: "战士" },
    { id: 2, name: "魔法师" },
    { id: 3, name: "游侠" },
  ],
  playerSpeed: 4,
  through: false,
};
